### ISSUE TITLE
linkedin 404

### ISSUE THREAD

**Issue by StackOverflowIsBetterThanAnyAI** [jayrajroshan/jayrajroshan#1]
Eyo, your linkedin link is no longer working. I receive a 404 error by pressing it.

**Comment by StackOverflowIsBetterThanAnyAI** [comment]
Your linkedin link should be: https://www.linkedin.com/in/jayrajroshan/
but it currently is: https://www.linkedin.com/in/jayraj-roshan/

**Comment by jayrajroshan** [comment]
Thanks for the heads-up, fixed.
